apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: laliga
type: Opaque
stringData:
  FOOTBALL_API_KEY: "your_football_api_key_here"
  EMAIL_USER: "your_email@example.com"
  EMAIL_PASS: "your_brevo_api_key_here"
